language: ruby
rvm: 2.0.0
sudo: required

before_install:
  # Fix error: Incorrect file permissions (664)
  - chmod 644 Formula/*.rb
  - umask 022
  - export TRAVIS_COMMIT="$(git rev-parse --verify -q HEAD)"
  - if [ -f ".git/shallow" ]; then
      travis_retry git fetch --unshallow;
    fi
  - HOME=/home/linuxbrew
  - sudo mkdir $HOME
  - sudo chown "$USER:" $HOME
  - mkdir $HOME/.linuxbrew
  - curl -L https://github.com/Linuxbrew/brew/tarball/master | tar xz -m --strip 1 -C $HOME/.linuxbrew
  - PATH="$HOME/.linuxbrew/bin:$HOME/.linuxbrew/sbin:$PATH"
  - rm -rf "$(brew --repo $TRAVIS_REPO_SLUG)"
  - mkdir -p "$(brew --repo $TRAVIS_REPO_SLUG)"
  - rsync -az "$TRAVIS_BUILD_DIR/" "$(brew --repo $TRAVIS_REPO_SLUG)"
  - export TRAVIS_BUILD_DIR="$(brew --repo $TRAVIS_REPO_SLUG)"
  - cd "$(brew --repo $TRAVIS_REPO_SLUG)"
  - export HOMEBREW_DEVELOPER="1"
  - ulimit -n 1024

script:
  - brew test-bot

notifications:
  slack:
    secure: PvK4LXijxgFTbT6SvWUveluJdbe7AfnJ+Ip/xb2gVRsq71DHSi96OtaEZq+qAvU6UU07VaCY/55cTb+HZE1twCOE4aE4l6iJONVmwIb+s9bGQfV9+H/r+y+J1EJzIzAfTbsn4mGJpkG9e2326c0vGcM/lFpHH0qarhOEYs4jLt17Ijg4mk+I5jLIOZ2vZsC7IZ0W8oe7Qzomyyfzj5XW2kUa41e8CgZf4byqAvnVpPpfvkm/rODGPREOmcpOr2Pu8fhNLrswXRlhgakZgi5JPPdaRocIhnbRbyqE2Qngnlk/wzno1e3NZYDcxTa5xAgAa5h/TIpyLeB/pXfpc1n5RuP7BjA/mZSYaG5Dg1IIvGPu/23+HlZ9umMn0E0f5j3EsV66CwErJGChm6hN7xPAxLz1Mj9v2E3CIDjyYcg/aZ+O27oaUlGoBGrX51g8poq6LhG+SxHx/VkDAJ+X4T56EQYTCA+ezEIs6KdWZl7AB4ztHqTe7w4YJIIhh509iViFKX4pJdQnajNf97IvRl9hHsLa9k9GuLWOQvxjkEJ/1LSfVkNEfPxHd2btIVdg6DQsVrxyfwufF+KlQDKNHR4Jbz+KEvrWIbXWQAj+2g7xwj5l2/Tyv69gR7FqBpSxh+Ue7wrWrVCIkzn/BEU4H0nHGR5D4dOwmgiOxXVhEZjYqjU=
  email:
    on_success: never
    on_failure: always
