language: ruby
rvm: 2.0.0
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml-parser-perl libxml-sax-perl
  - DEBIAN_FRONTEND=noninteractive sudo apt-get autoremove -y --purge libblas-dev libicu-dev libidn11-dev libjasper-dev libjbig-dev libkrb5-dev libncurses5-dev libpcre3-dev libtinfo-dev libwebp-dev libwmf-dev libxml2-dev llvm-3.4 mysql-common
  # Fix error: Incorrect file permissions (664)
  - chmod 0644 Formula/*.rb
  - umask 022
  - export TRAVIS_COMMIT="$(git rev-parse --verify -q HEAD)"
  - if [ -f ".git/shallow" ]; then
      travis_retry git fetch --unshallow;
    fi
  - HOME=/home/linuxbrew
  - sudo mkdir $HOME
  - sudo chown "$USER:" $HOME
  - LINUXBREW=$HOME/.linuxbrew
  - git clone https://github.com/Linuxbrew/brew.git $LINUXBREW
  - export PATH="$LINUXBREW/bin:$LINUXBREW/sbin:$PATH"
  - TRS="$(brew --repo $TRAVIS_REPO_SLUG)"
  - rm -rf "$TRS"
  - mkdir -p "$TRS"
  - rsync -az "$TRAVIS_BUILD_DIR/" "$TRS"
  - export TRAVIS_BUILD_DIR="$TRS"
  - cd "$(brew --repo)"
  - export HOMEBREW_DEVELOPER=1
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_VERBOSE=1 HOMEBREW_VERBOSE_USING_DOTS=1
  - ulimit -n 1024
  - brew tap homebrew/dupes
  - brew tap linuxbrew/xorg

script:
  - brew test-bot

notifications:
  slack:
    secure: PvK4LXijxgFTbT6SvWUveluJdbe7AfnJ+Ip/xb2gVRsq71DHSi96OtaEZq+qAvU6UU07VaCY/55cTb+HZE1twCOE4aE4l6iJONVmwIb+s9bGQfV9+H/r+y+J1EJzIzAfTbsn4mGJpkG9e2326c0vGcM/lFpHH0qarhOEYs4jLt17Ijg4mk+I5jLIOZ2vZsC7IZ0W8oe7Qzomyyfzj5XW2kUa41e8CgZf4byqAvnVpPpfvkm/rODGPREOmcpOr2Pu8fhNLrswXRlhgakZgi5JPPdaRocIhnbRbyqE2Qngnlk/wzno1e3NZYDcxTa5xAgAa5h/TIpyLeB/pXfpc1n5RuP7BjA/mZSYaG5Dg1IIvGPu/23+HlZ9umMn0E0f5j3EsV66CwErJGChm6hN7xPAxLz1Mj9v2E3CIDjyYcg/aZ+O27oaUlGoBGrX51g8poq6LhG+SxHx/VkDAJ+X4T56EQYTCA+ezEIs6KdWZl7AB4ztHqTe7w4YJIIhh509iViFKX4pJdQnajNf97IvRl9hHsLa9k9GuLWOQvxjkEJ/1LSfVkNEfPxHd2btIVdg6DQsVrxyfwufF+KlQDKNHR4Jbz+KEvrWIbXWQAj+2g7xwj5l2/Tyv69gR7FqBpSxh+Ue7wrWrVCIkzn/BEU4H0nHGR5D4dOwmgiOxXVhEZjYqjU=
  email:
    on_success: never
    on_failure: always
