trigger: none
pr:
  autoCancel: true
  paths:
    include:
    - 'Formula/*'
  branches:
    include:
    - '*'
    exclude:
    - 'merge-*-*-*-*'

jobs:
- job: BuildLinuxbrewCoreBottles
  timeoutInMinutes: 360
  pool:
    vmImage: ubuntu-latest
  container:
    image: homebrew/brew
  steps:
  - script: printenv
    displayName: Azure printenv
  - bash: |
      sudo adduser $(whoami) linuxbrew
    displayName: Setup user
  - bash: |
      git config --global user.name LinuxbrewTestBot
      git config --global user.email testbot@linuxbrew.sh
    displayName: Setup git
  - bash: |
      git checkout -b test
      git fetch origin "master:master" "pull/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/head:pr"
      git checkout pr
      rm -rf $(brew --repository $BUILD_REPOSITORY_NAME)
      ln -s $BUILD_REPOSITORY_LOCALPATH $(brew --repository $BUILD_REPOSITORY_NAME)
    displayName: Setup tap
  - bash: brew update-reset $(brew --repository)
    displayName: Update Homebrew
  - bash: |
      mkdir /tmp/bottles
      cd /tmp/bottles
      brew test-bot \
        --tap=homebrew/core \
        --bintray-org=linuxbrew \
        --git-name=LinuxbrewTestBot \
        --git-email=testbot@linuxbrew.sh \
        --keep-old
      if [ $? -gt 0 ]; then
        echo "$SYSTEM_PULLREQUEST_SOURCECOMMITID" > build_status.txt
        exit 1
      fi
    displayName: Build bottles
    continueOnError: true
  - bash: |
      cp /tmp/bottles/*.bottle.* $BUILD_ARTIFACTSTAGINGDIRECTORY
      cp /tmp/bottles/build_status.txt $BUILD_ARTIFACTSTAGINGDIRECTORY || true
    displayName: Copy bottles
    condition: always()
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: bottle-linux
      targetPath: $(Build.ArtifactStagingDirectory)
    displayName: Publish bottles
    condition: always()

