name: Build bottles.

on:
  pull_request:
    paths:
      - 'Formula/*'

jobs:
  build-bottles:
    if: startsWith(github.event.pull_request.title, 'Merge') == false
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
      options: --user linuxbrew
    steps:
      - name: Checkout tap
        uses: actions/checkout@v2
      - name: Setup tap
        run: |
          rm -rf $(brew --repository ${{github.repository}})
          ln -s $GITHUB_WORKSPACE $(brew --repository ${{github.repository}})
      - name: Build bottles
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot \
            --tap=homebrew/core \
            --keep-old
      - name: Copy bottles
        if: always()
        run: |
          cp -a ~/bottles $GITHUB_WORKSPACE
      - name: Upload bottles
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: bottles
