name: Generate formulae.brew.sh data.

on:
  push:
    branches:
      - master

jobs:
  generate:
    if: github.repository == 'Homebrew/homebrew-core'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: Homebrew/actions/git-ssh@master
        with:
          git_user: BrewTestBot
          git_email: homebrew-test-bot@lists.sfconservancy.org
          key: ${{ secrets.FORMULAE_DEPLOY_KEY }}
      - run: |
          brew update-reset "$(brew --repository)"
          brew tap "$GITHUB_REPOSITORY"
          brew update-reset "$(brew --repository "$GITHUB_REPOSITORY")"

          export PATH="$(brew --repo)/Library/Homebrew/vendor/portable-ruby/current/bin:$PATH"

          git clone --depth=1 git@github.com:Homebrew/formulae.brew.sh
          cd formulae.brew.sh

          # setup analytics
          echo "$ANALYTICS_JSON_KEY" > ~/.homebrew_analytics.json

          # run rake (without a rake binary)
          ruby -e "load Gem.bin_path('rake', 'rake')"

          # commit and push generated files
          git add _data/formula api/formula formula

          if ! git diff --exit-code HEAD -- _data/analytics _data/formula api/formula formula cask; then
            git commit -m "formula: update from ${GITHUB_REPOSITORY} push" _data/analytics _data/formula api/formula formula
            git fetch
            git rebase origin/master
            git push
          fi
        env:
          ANALYTICS_JSON_KEY: ${{ secrets.ANALYTICS_JSON_KEY }}

  generate-linux:
    if: github.repository == 'Homebrew/linuxbrew-core'
    runs-on: ubuntu-latest
    container: homebrew/brew:latest

    steps:
      - uses: actions/checkout@master
      - uses: Homebrew/actions/git-ssh@master
        with:
          git_user: BrewTestBot
          git_email: homebrew-test-bot@lists.sfconservancy.org
          key: ${{ secrets.FORMULAE_DEPLOY_KEY }}
      - run: |
          brew update-reset "$(brew --repository)"
          brew tap "$GITHUB_REPOSITORY"
          brew update-reset "$(brew --repository "$GITHUB_REPOSITORY")"

          export PATH="$(brew --repo)/Library/Homebrew/vendor/portable-ruby/current/bin:$PATH"

          # create stubs so build dependencies aren't incorrectly flagged as missing
          for i in python svn unzip xz
          do
            touch /usr/bin/$i
            chmod +x /usr/bin/$i
          done

          git clone git@github.com:Homebrew/formulae.brew.sh
          cd formulae.brew.sh

          # setup analytics
          brew install jq
          echo "$ANALYTICS_JSON_KEY_B64" | base64 --decode | jq . > ~/.homebrew_analytics.json

          # run rake (without a rake binary)
          ruby -e "load Gem.bin_path('rake', 'rake')" linux_formula_and_analytics

          # commit and push generated files
          git add _data/analytics-linux _data/formula-linux api/formula-linux formula-linux

          if ! git diff --no-patch --exit-code HEAD -- _data/analytics-linux _data/formula-linux api/formula-linux formula-linux; then
            git commit -m "formula-linux: update from ${GITHUB_REPOSITORY} push" _data/analytics-linux _data/formula-linux api/formula-linux formula-linux
            git fetch
            git rebase origin/master
            git push
          fi
        env:
          ANALYTICS_JSON_KEY_B64: ${{ secrets.ANALYTICS_JSON_KEY_B64 }}
