name: Upload bottles.

on:
  push:
    branches:
      - master
    paths:
      - 'Formula/*'

jobs:
  upload-bottles:
    if: startsWith(github.event.head_commit.message, 'Merge') == false && github.event.pusher.name != 'BrewTestBot'
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    steps:
      - name: Determine associated pull request
        uses: actions/github-script@0.9.0
        id: pr
        with:
          script: |
            const prs = await github.repos.listPullRequestsAssociatedWithCommit({
              ...context.repo,
              commit_sha: context.payload.head_commit.id
            })
            console.log(prs.data.length + " prs")
            if (prs.data.length === 0) {
              throw "No pull requests are associated with this merge commit."
            }
            core.setOutput("number", prs.data[0].number.toString())
            core.setOutput("head_sha", prs.data[0].head.sha)
      - name: Download workflow artifacts
        uses: Homebrew/actions/download-artifact@master
        with:
          github_token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          workflow: build-bottles.yml
          commit: ${{steps.pr.outputs.head_sha}}
          name: bottles
          path: bottles
      - name: Upload and publish bottles
        env:
          HOMEBREW_BINTRAY_USER: LinuxbrewTestBot
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
        if: steps.pr.outputs.number != 0
        run: |
          cd bottles
          brew update-reset $(brew --repo ${{github.repository}})
          brew test-bot \
            --tap=homebrew/core \
            --bintray-org=linuxbrew \
            --ci-upload \
            --publish \
            --keep-old
      - name: Push bottle commit
        env:
          GIT_COMMITTER_NAME: ${{github.event.pusher.name}}
          GIT_COMMITTER_EMAIL: ${{github.event.pusher.email}}
        if: steps.pr.outputs.number != 0
        run: |
          cd $(brew --repo ${{github.repository}})
          git commit --amend --no-edit
          git show --pretty=fuller
          for try in $(seq 5); do
            git fetch
            git rebase origin/master
            if git push https://x-access-token:${{secrets.HOMEBREW_GITHUB_API_TOKEN}}@github.com/${{github.repository}} master; then
              exit 0
            else
              sleep $(shuf -i 3-10 -n 1)
            fi
          done
          exit 1
      - name: Post comment on failure
        if: failure()
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          script: |
            const run_id = process.env.GITHUB_RUN_ID
            const actor = process.env.GITHUB_ACTOR
            const pr = ${{steps.pr.outputs.number}}

            console.log("run_id=" + run_id)
            console.log("actor=" + actor)
            console.log("pr=" + pr)

            const repository = context.repo.owner + '/' + context.repo.repo
            const url = 'https://github.com/' + repository + '/actions/runs/' + run_id

            github.issues.createComment({
              issue_number: pr,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '@' + actor + ' upload bottles job failed: ' + url
            })
